// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"engineering/internal/engineering_service/domain"
	"engineering/internal/engineering_service/services"
)

// Injectors from wire.go:

func InitUserAPI() *services.UserServiceImpl {
	user := domain.NewUser()
	userLog := domain.NewUserLog()
	userServiceImpl := services.NewUserServiceImpl(user, userLog)
	return userServiceImpl
}
